#!/usr/bin/env bash

this_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cat <<EOF > "$HOME/.slate.js"
// Generated by $this_dir/${BASH_SOURCE[0]}
S.source('${this_dir}/utils.js');
S.source('${this_dir}/screen.js');
S.source('${this_dir}/slate.js');
EOF
